### ISSUE TITLE
Google Fonts Onboarding: QA FAIL: Each font in a family must have the same set of vertical metrics values.

### ISSUE THREAD

**Issue by eliheuer** [reddit/redditsans#1]
Google Fonts onboarding uses [FontBakery](https://github.com/fonttools/fontbakery) for QA. All `FAIL` level checks from the `universal`, `opentype` and `googlefonts` profiles must be passing in order to onboard fonts to Google Fonts. Exceptions can be made if necessary.

See the Quality Assurance section of the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) for more information: https://googlefonts.github.io/gf-guide/qa.html

🔥 **FAIL: Each font in a family must have the same set of vertical metrics values.**
([com.google.fonts/check/family/vertical_metrics](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/family/vertical_metrics))

🔥 **FAIL usWinAscent is not the same across the family:**
Reddit Sans ExtraBold Italic: 2564
Reddit Sans Bold: 2455
Reddit Sans ExtraBold: 2492
Reddit Sans SemiBold: 2416
Reddit Sans Italic: 2441
Reddit Sans Light: 2309
Reddit Sans: 2356
Reddit Sans SemiBold Italic: 2496
Reddit Sans Light Italic: 2400
Reddit Sans Bold Italic: 2530 [code: usWinAscent-mismatch]

🔥 **FAIL usWinDescent is not the same across the family:**
Reddit Sans ExtraBold Italic: 580
Reddit Sans Bold: 603
Reddit Sans ExtraBold: 624
Reddit Sans SemiBold: 583
Reddit Sans Italic: 543
Reddit Sans Light: 523
Reddit Sans: 550
Reddit Sans SemiBold Italic: 559
Reddit Sans Light Italic: 530
Reddit Sans Bold Italic: 570

**See the vertical metrics section of the Google Fonts Guide for more information:** https://googlefonts.github.io/gf-guide/metrics.html

**Comment by eliheuer** [comment]
Of all the issues that need to be addressed for Google Fonts onboarding, this is the most important and urgent one, everything else is a somewhat minor issue.

**Comment by stephenhutchings** [comment]
This should be fixed in the latest version (v1.012) of the fonts.
