### ISSUE TITLE
Google Fonts Onboarding: QA FAIL: Do fonts have consistent underline thickness?

### ISSUE THREAD

**Issue by eliheuer** [reddit/redditsans#2]
Google Fonts onboarding uses [FontBakery](https://github.com/fonttools/fontbakery) for QA. All `FAIL` level checks from the `universal`, `opentype` and `googlefonts` profiles must be passing in order to onboard fonts to Google Fonts. Exceptions can be made if necessary.

See the Quality Assurance section of the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) for more information: https://googlefonts.github.io/gf-guide/qa.html

🔥 **FAIL: Fonts have consistent underline thickness?** ([com.google.fonts/check/family/underline_thickness](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/post.html#com.google.fonts/check/family/underline_thickness))

🔥 FAIL Thickness of the underline is not the same across this family. In order to fix this, please make sure that the underlineThickness value is the same in the 'post' table of all of this family font files.

Detected underlineThickness values are:
ofl/redditsans/RedditSans-ExtraBoldItalic.ttf: 150
ofl/redditsans/RedditSans-Bold.ttf: 136
ofl/redditsans/RedditSans-ExtraBold.ttf: 150
ofl/redditsans/RedditSans-SemiBold.ttf: 122
ofl/redditsans/RedditSans-Italic.ttf: 100
ofl/redditsans/RedditSans-Light.ttf: 81
ofl/redditsans/RedditSans-Regular.ttf: 100
ofl/redditsans/RedditSans-SemiBoldItalic.ttf: 122
ofl/redditsans/RedditSans-LightItalic.ttf: 81
ofl/redditsans/RedditSans-BoldItalic.ttf: 136

**See the Google Fonts Guide for more information:** https://googlefonts.github.io/gf-guide

**Comment by stephenhutchings** [comment]
This should be fixed in the latest version (v1.012) of the fonts.
