### ISSUE TITLE
Google Fonts Onboarding: QA FAIL: OS/2 fsType should not impose restrictions.

### ISSUE THREAD

**Issue by eliheuer** [reddit/redditsans#3]
Google Fonts onboarding uses [FontBakery](https://github.com/fonttools/fontbakery) for QA. All `FAIL` level checks from the `universal`, `opentype` and `googlefonts` profiles must be passing in order to onboard fonts to Google Fonts. Exceptions can be made if necessary.

See the [Quality Assurance](https://googlefonts.github.io/gf-guide/qa.html) section of the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) for more information: https://googlefonts.github.io/gf-guide/qa.html

🔥 **FAIL: Checking OS/2 fsType does not impose restrictions.** ([com.google.fonts/check/fstype](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/fstype))

🔥 **FAIL** In this font fsType is set to 8 meaning that:
The font may be embedded but must only be installed temporarily on other systems.

No such DRM restrictions can be enabled on the Google Fonts collection, so the fsType field must be set to zero (Installable Embedding) instead.

**See the Google Fonts Guide for more information:** https://googlefonts.github.io/gf-guide

**Comment by stephenhutchings** [comment]
This should be fixed in the latest version (v1.012) of the fonts.
