### ISSUE TITLE
Google Fonts Onboarding: QA FAIL: Space and non-breaking space should have the same width

### ISSUE THREAD

**Issue by eliheuer** [reddit/redditsans#9]
Google Fonts onboarding uses [FontBakery](https://github.com/fonttools/fontbakery) for QA. All `FAIL` level checks from the `universal`, `opentype` and `googlefonts` profiles must be passing in order to onboard fonts to Google Fonts. Exceptions can be made if necessary.

See the [Quality Assurance](https://googlefonts.github.io/gf-guide/qa.html) section of the [Google Fonts Guide](https://googlefonts.github.io/gf-guide/) for more information: https://googlefonts.github.io/gf-guide/qa.html

🔥 **FAIL: Space and non-breaking space have the same width?** ([com.google.fonts/check/whitespace_widths](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/whitespace_widths))

🔥 **FAIL** Space and non-breaking space have differing width: The space glyph named space is 573 font units wide, non-breaking space named (uni00A0) is 578 font units wide, and both should be positive and the same. GlyphsApp has "Sidebearing arithmetic" (https://glyphsapp.com/tutorials/spacing) which allows you to set the non-breaking space width to always equal the space width.

**See the Google Fonts Guide for more information:** https://googlefonts.github.io/gf-guide

**Comment by stephenhutchings** [comment]
This should be fixed in the latest version (v1.012) of the fonts.
